README.md
This fixes an issue where the documentation and code have got out-of-sync.
As far as I know, the Error Handler Middleware now does not need to be imported anymore since it should be loaded by use/createExpressServer's `middlewareDirs`.  That being said, maybe not everyone uses that option and may still need to manually include the files.
I am referring to the following:
-2. Load created error handler before app bootstrap:		
-		
-    ```typescript		
-    import "reflect-metadata";		
-    import {createExpressServer} from "routing-controllers";		
-    import "./UserController";		
-    import "./CustomErrorHandler"; // here we load it		
-    createExpressServer().listen(3000);		
-    ```		
-
Long story short: maybe the above shouldn't be removed.
=> Fixes Error Handler documentation

README.md, package.json, sample/sample12-session-support/UserController.ts, sample/sample12-session-support/app.ts, src/decorator/params.ts, src/driver/ExpressDriver.ts, src/driver/KoaDriver.ts, src/metadata/types/ParamTypes.ts, test/functional/action-params.spec.ts, typings.json
Implemented issue #30.
Works for injecting whole session object - `@Session() session: Express.Session` or with single object from session - `@Session("objectName") object: ObjectType`.
=> Added @Session decorator

package.json
this is required for typescript to find and resolve the module and its typings :)
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
=> missing "typings" in package.json file

README.md, package.json, sample/sample13-koa-views-render/BlogController.ts, sample/sample13-koa-views-render/app.ts, sample/sample13-koa-views-render/blog.html, src/driver/KoaDriver.ts, test/functional/render-decorator.spec.ts
Closes #59
The KoaDriver render was not completed, it was using the Express way of rendering html templates using Template engines that were loaded into express.
I have decided that I prefer Koa over express so have played around with the KoaDriver to try get the render to work for Koa.
I have decided to use [Koa-views](https://github.com/queckezz/koa-views) as the rendering middleware, as it allows for loading of different rendering engines easily. In the tests I have edited the Koa before section to load up the rendering middleware and load the handlebars engine by default.
The fix I have applied is not very neat but works for now, it creates a middleware in the handleSuccess method of the KoaDriver as I needed access to Koa's context which Koa-views extends and adds the render method …
=> Koa Render Closes #59

README.md, test/functional/global-options.spec.ts
Docs and tests had a typo in the usage of `useClassTransformer`, was written `useConstructorUtils`.
=> fix(useClassTransformer): fixing docs and tests

src/ActionCallbackOptions.ts, src/driver/ExpressDriver.ts, test/functional/express-global-before-error-handling.spec.ts
When throwing an Exception from lower layers of the app, the correct exception wouldn't pop in the global `ErrorMiddleware`. 
Instead, the error`TypeError: Cannot read property 'handle' of undefined` would raise. This was caused by `ExpressDriver` when trying to handle the error. `this` reference was not defined properly in `ExpressDriver.registerMiddleware`. 
Using an anonymous function for the inner middleware, so that `this` is a reference to `ExpressDriver` and not a reference to the inner middleware function.
=> Exception throwing error fixed

src/ParamHandler.ts, src/driver/KoaDriver.ts, test/functional/action-params.spec.ts
Maybe you could `throw new` instead of `return Promise.reject(new` but I'm not sure whether the exception will be handled or remain uncaught, so I decided to fix it this way.
Fixes #71 
PS: `throw new` is the only correct way
=> Fix required error handling

README.md, package.json, src/driver/KoaDriver.ts, test/functional/action-params.spec.ts
Uses koa-multer instead of koa-router-multer as it seems more popular. All references and tests should be up to date, but let me know if I missed anything.
=> Implemented Koa file upload

README.md
Getting an error about loadControllers:
```
server-typestack (master<>)$ tsc
src/app-typestack.ts(2,26): error TS2305: Module '"/Users/bencreasy/code/projects/starters/react-redux-typescript-starter-kit/node_modules/routing-controllers/index"' has no exported member 'loadControllers'.
```
Also a search shows no evidence of a loadControllers function: https://github.com/pleerock/routing-controllers/search?utf8=%E2%9C%93&q=loadControllers
=> Remove reference to loadControllers

src/metadata/ActionMetadata.ts, test/functional/global-options.spec.ts, test/functional/redirect-decorator.spec.ts
Routes using regex had some issues:
- They didn't work when `routePrefix` was provided starting with `/`
- The did work if `/` was omitted from `routePrefix`, but then all other routes started failing
The following changes were made to target this issue:
- Changed the way the full route path was created at `ActionMetadata` to match the resulting regex pattern with those routes created without regex usage.
- Added missing tests for regex routes for an an app that sets the `routePrefix` param
=> Fix routePrefix handling for routes using regex

README.md
Hi there,
I've noticed a small bug in the interceptor documentation. There is uneeded decorator `@Interceptor` in the section: https://github.com/pleerock/routing-controllers#interceptor-classes. It makes it global which is not desired behaviour.
PS. Sorry for whitespaces "mess" - my editor automatically changed that. Here's the actual change:
https://github.com/pleerock/routing-controllers/pull/189/files#diff-04c6e90faac2675aa89e2176d2eec7d8L1033
=> Fix instructions about creating interceptors

README.md, src/RoutingControllers.ts, src/RoutingControllersOptions.ts, src/decorator/Body.ts, src/decorator/BodyParam.ts, src/decorator/CookieParam.ts, src/decorator/CurrentUser.ts, src/decorator/HeaderParam.ts, src/decorator/QueryParam.ts, src/decorator/Session.ts, src/decorator/UploadedFile.ts, src/decorator/UploadedFiles.ts, src/index.ts, src/metadata-builder/MetadataBuilder.ts, src/metadata/ActionMetadata.ts, test/functional/defaults.spec.ts, test/functional/express-defaults.spec.ts
Hi @pleerock,
Your library is great. And I think it would be better if we are able to set default values.
For example, if method is `void` or `Promise<void>`, I expected it to return `204` rather than `404` by default. If there is any exception, then I will override by `OnUndefined` decorator.
The other setting I prefer to set is `required` option, I want all parameters to required by default. And I can override with the param options.
This would give more flexibility to other projects which have different convention, and improve readability since there is less number of settings needed to be specified.
Thank you,
=> allow default options

src/driver/express/ExpressDriver.ts
Really great module 👍 
One requirement in our project is to differentiate Unauthorized and Forbidden code during authorization process.
That's why I added an catch to the authorizationChecker, to be able to throw HttpErrors the same as in controllers.
I think that could be helpful for others too.
```typescript
createExpressServer({
authorizationChecker: async (action: Action, roles: string[]) => {
const token = action.request.headers["authorization"];
if (!token)
throw new UnauthorizedError();
const user = await getEntityManager().findOneByToken(User, token);
if (!user)
throw new UnauthorizedError();
if (!roles.length)
return true;
if (roles.find(role => user.roles.indexOf(role) !== -1))
return true;
throw new ForbiddenError();
}
});
```
Thanks
=> handle custom errors thrown by authorization checker

CHANGELOG.md, src/driver/express/ExpressDriver.ts, src/driver/koa/KoaDriver.ts
This PR fixes #250.  
Until now files where accepted before checking the authorization rights. Now both the Koa driver and Express driver correctly check the authorization first.
closes #250
=> fix(Drivers): check auhorization before accepting files

src/metadata/ActionMetadata.ts
- Updated the ActionMetadata `callMethod` method to use the ControllerMetadata `instance` getter once.
- Fixes https://github.com/pleerock/routing-controllers/issues/239
=> Controller constructer called twice

test/fakes/global-options/SessionMiddleware.ts
This PR adds two additional settings to the express test session. Those settings were optional, but their default values are now deprecated.
Sources:
* https://github.com/expressjs/session#saveuninitialized
* https://github.com/expressjs/session#resave
=> Fixed express-session deprecation

test/functional/action-params.spec.ts, test/functional/class-transformer-options.ts, test/functional/class-validator-options.spec.ts
This PR replaces all occurrences of mocha's `should` interface for the `expect` interface… You know, for consistency.
=> Replaced `should` for `expect`

src/driver/koa/KoaDriver.ts, test/functional/action-params.spec.ts
This PR fixes #156.
One of the new tests do fail when running under Gulp, but works fine when ran directly from mocha. I have no idea why.
=> Koa multipart body

package.json, src/driver/express/ExpressDriver.ts, src/driver/koa/KoaDriver.ts, test/functional/controller-methods.spec.ts
Solving #231.
I decided to throw `NotFoundError` when `undefined` is returned from an action. This should let error handler decide about formatting the JSON response for JSON controllers and text/plain or html for text responses.
However I think we should place the info about the route where the undefined has been returned. @pleerock @NoNameProvided do you have any idea about what info and how formated the error message should be? 😕
=> Fix 404 text content-type for JSON controllers

src/driver/express/ExpressDriver.ts, src/driver/koa/KoaDriver.ts, test/functional/auth-decorator.spec.ts
=> Fix sync and async auth checker bug

package.json
This PR set `NODE_ENV` to `test`. What will prevent Express default error handler to print error messages to the console.
Works on Windows, MacOs, Linux.
=> chore: set NODE_ENV to test when running tests

src/driver/BaseDriver.ts, src/driver/express/ExpressDriver.ts, src/driver/koa/KoaDriver.ts, test/functional/action-params.spec.ts, test/functional/special-result-send.spec.ts, test/resources/sample-text-file.txt
Reimplementing PR #182.
Fixes #228, fixes #180 and fixes #183.
=> Add support for returning Buffer and streams from action

README.md, src/driver/express/ExpressDriver.ts, src/driver/koa/KoaDriver.ts, test/functional/action-params.spec.ts
I've added some tests for the documented way to write to the response directly, as in: https://github.com/pleerock/routing-controllers#using-request-and-response-objects. It looks like #241 broke this usage pattern.
=> Directly calling response

src/driver/express/ExpressDriver.ts, test/functional/test-utils.ts
We have some bugs on `routing-controllers` codebase that are somewhat silent: they just log an unhandled rejection. Since that's deprecated and undesirable (future node versions will terminate the process on unhandled rejections), I've augmented `assertRequest` so it fails tests when it happens.
The `assertRequest` augmentation made another bug surface (expressjs/express#2116), so I fixed it on this PR as well.
=> Patch to treat unhandled rejections as test failures

README.md, src/driver/BaseDriver.ts, test/functional/express-error-handling.spec.ts
Hi,
it would be great to have the ability to define a custom toJSON transformation of Errors before they are sent to the client.
UseCase:
We want to censor our custom Errors (extending HttpError) before they are leaving the server.
Therefore we thought to simply implement a toJSON method, like you can override the toString.
```ts
export class CustomError extends HttpError {
public publicData: string;
public secretData: string;
constructor( httpCode: number, publicData: string, publicData: string ) {
super( httpCode );
Object.setPrototypeOf(this, CustomError.prototype);
this.publicData = publicData;
this.secretData = secretData;
}
toJSON () {
return {
httpCode: this.httpCode,
publicData: this.publicData
};
}
}
```
Best Regards
=> ErrorHandler: invoke class specific toJSON transformation

.travis.yml
There is 2 kind of users: 
- ones trying out routing-controllers
- and production users 
Production users (hopefully) uses LTS version of NodeJS and other users who experience with the project can be asked to update to the latest stable or LTS release. So supporting non LTS releases is just extra effort we should avoid. 
If I could not convince you, here is also an [article](https://medium.com/@mikeal/stop-supporting-old-releases-70cfa0e04b0c) about this from Mikeal.
=> chore: support only LTS and stable version

src/metadata-builder/MetadataBuilder.ts
Interceptor's param { priority: nubmer } is not work
=> fix(Interceptors): order of  global interceptors

README.md
Some response functions don't actually return the response object, which
is why it needs to be returned directly.
This took me some time to figure out, so I added an example.
=> chore: add another example for using the response directly

README.md, src/decorator/All.ts, src/driver/express/ExpressDriver.ts, src/index.ts, src/metadata/types/ActionType.ts, test/functional/controller-methods.spec.ts
I added support for routes which match all HTTP methods.
A change to the action type vs. request method check in `routeHandler` in the Express driver was required. However, being unfamiliar with the project source I'm not entirely sure this is the only location where such a change is required.
=> Add support for wildcard "all" routes

src/driver/express/ExpressDriver.ts, src/driver/koa/KoaDriver.ts
This fix prevents a single request from resulting in multiple route executions by adding a guard.
This is also required for my other PR #536.
Fixes: #547, #491, and more similar issues
=> Prevent multiple route executions per request

README.md
Added service decorator to default DI controller example (TypeDI) as explained in issue
Doesn't fix #642 but helps to understand and prevent issue duplications
=> docs: added TypeDI service decorator to example in README

src/util/importClassesFromDirectories.ts
Right now you can not use TSX files to define routes. 
We are using React with SSR (only some routes) but the `.tsx` are not loaded by `importClassesFormDirectories` because supporting files are: `.ts` & `.js`
Example:
```javascript
import { Controller, Get, Render } from 'routing-controllers';
import { renderToString } from 'react-dom/server';
import React from 'react';
const Hello = () => <p>Hi!</p>
@Controller()
export class HomeController {
constructor(private getBanners: GetBanners) {}
@Get(`/`)
@Render('home.njk')
getHome(): void {
// Render React Component
const content = renderToString(<Hello />);
return { metadata: { title: 'Home' }, content };
}
}
```
That route will never appear (return 404)
=> feat: load TSX files in `importClassesFormDirectories`

src/ActionParameterHandler.ts, test/ActionParameterHandler.spec.ts
The usage of UUID instead of id in routes like http://0.0.0.0:3000/api/products/04879b32-c329-48d7-a652-818794b684f1
Is trying to build JSON object while returning a raw parameter(UUID) provided.
Ref: https://github.com/typestack/routing-controllers/issues/703
- [s] tests are added for the changes I made (if any source code was modified)
The conditions the inside `normalizeParamValue` now excluding "param" type, keeping UUID strings untouched
=> feat: Impossible to use UUID as param for object construction #706

README.md, src/ActionParameterHandler.ts, src/decorator-options/ParamOptions.ts, src/decorator/QueryParam.ts, src/metadata/ParamMetadata.ts, src/metadata/args/ParamMetadataArgs.ts, test/functional/action-params.spec.ts
Fixes #389, Fixes #320, Fixes #123
The idea is to parse query parameters as it is used to be. I added some exemple in the README, and in the tests :
You can use `isArray` option to get a query param array. This will cast the query param :
```typescript
@Get("/users/by-multiple-ids")
getUsers(@QueryParam("ids", { isArray: true}) ids: string[]) {
}
```
`GET /users/by-multiple-ids?ids=a` → `ids = ['a']`
`GET /users/by-multiple-ids?ids=a&ids=b` → `ids = ['a', 'b']`
You can combine use `isArray` option with `type` option to get a query param array of one type. This will cast the query param :
```typescript
@Get("/users/by-multiple-ids")
getUsers(@QueryParam("ids", { isArray: true, type: Number}) ids: number[]) {
}
```
`GET …
=> feat: add cast array to expected array query params

README.md
The docs assume that routes will always be in a subfolder of express app which may not be true and in which case the docs could use a touchup.
E.g. in a hexagonal architecture, Express is considered an adapter and api routes are ports so you may need something like:
```ts
useExpressServer(this.app, {
routePrefix: '/api',
controllers: [path.join(__dirname, '../../ports/api/routes/**/*.*')],
});
```
=> docs: Update use of glob patterns in docs in README.md

README.md
Most likely the intent of this lambda was to return an object, and not to have a code-block with labels.
fixes #742
=> fix: Fixed example in README.md

src/ActionParameterHandler.ts
`@Param('id') id: number` is not validated and accepts `NaN` as value in case of invalid `id`.
For example, if the following URL is accessed (`http://example.com/users/asdf`), instead of throwing an error, the `id` value is parsed to `NaN`. `InvalidParamError(value, parameterName, parameterType)` should be thrown instead.
The problem is due to how the checking of the result of the cast operation is done. `NaN` is not equal to `NaN`. Because of this it is necessary to use `Number.isNaN()`.
**Example**
```
@JsonController('/users')
class UserController {
@Get('/:id')
get (@Param('id') id: number) {
console.log(id);
}
}
```
**Result**
`GET http://example.com/users/1234` -> `1234`
`GET http://example.com/users/asdf` -> `NaN` …
=> fix: check if a number is NaN in ActionParameterHandler

sample/sample11-complete-sample-express/app.ts
This pull request issues minor changes to the [sample 11](https://github.com/typestack/routing-controllers/tree/develop/sample/sample11-complete-sample-express)(complete-sample-express)
=> refactor: sample 11

src/ActionParameterHandler.ts, test/ActionParameterHandler.spec.ts
Fix null typecheck in parameter validation
fixes #655
=> fix: null typecheck in parameter validation

test/utilities/axios.ts
Disable keepAlive for test requests until axios lib is fixed (currently trying to reuse disconnected sockets)
Tests
=> fix: disable keepAlive in test requests until axios is fixed

README.md, docs/lang/chinese/README.md, lang/chinese/README.md, src/RoutingControllersOptions.ts, src/driver/BaseDriver.ts, src/driver/koa/KoaDriver.ts
Fix updated dependency usage for koa and update docs
fixes #692
=> fix: koa deps

src/util/importClassesFromDirectories.ts
normalize glob patterns to use / instead \ for both windows and *nix.
fixes #987, #980
=> fix: normalize glob patterns for windows

src/driver/koa/KoaDriver.ts, test/functional/koa-trailing-slash.spec.ts
Before the update, `@koa/router` allowed path declared with a trailing slash to be accessible both with or without trailing slash
```ts
router.get('/user/', handler)
// GET /user -> 200
// GET /user/ -> 200
```
After the update, only trailing slash path is accessible. This makes registering nested routes with `@Get('/')` infeasible, when one does not use trailing slashes for URLs.
```ts
@JsonController('/user')
export class UserController {
@Get('/') // <-- this causes the route to become `/user/`
getUser() {}
}
```
Proposed change, restricted in scope to affected KoaDriver only, removes the trailing slash if one appears in the route (aside from `/`). `@koa/router` allows such paths to be accessed both with and without trailing slash, as before.
Please note `@Get('/')` is what official …
=> Fix: Remove trailing slash from route path in KoaDriver

src/metadata-builder/MetadataBuilder.ts, test/unit/controller-inheritance.spec.ts
A more concise re-implementation of the `createActions()` method. Essence of this is that the `target` property of the metadata is not changed in-place, which hindered using a base class multiple times.
fixes #1124
=> fix: createActions should not garble baseclass metadata

CHANGELOG.md, package-lock.json, package.json, src/driver/koa/KoaDriver.ts, src/metadata-builder/MetadataBuilder.ts, test/functional/koa-trailing-slash.spec.ts, test/unit/controller-inheritance.spec.ts
This PR creates release v0.10.4
=> feat: release v0.10.4

src/CurrentUserChecker.ts, src/index.ts
This PR introduces a change to the `CurrentUserChecker` type definition to support generics, allowing for more precise type inference and usage in projects utilizing `routing-controllers`.
- The `CurrentUserChecker` type definition has been modified to accept a generic type parameter `User`. This parameter defaults to `any`, ensuring backward compatibility.
- The return type has been updated to include `User | null` in addition to `Promise<User | null>`. This change enhances type safety by allowing the function to explicitly specify a nullable user object, which aligns better with TypeScript practices where explicit types are preferable for nullability.
Previously, `CurrentUserChecker` was typed to return `any` or `Promise<any>`, which did not leverage TypeScript's full capabilities for …
=> feat: enhanced typing for CurrentUserChecker by introducing generics

src/decorator-options/BodyOptions.ts
=> Updated links in comments
