README.md

Update example in order to reflect commit 867308999dd576fd7baf43818736bc30652af0aa in src/index.ts @@ -9,17 +18,37 @@

Update example to reflect function rename

---

README.md
src/driver/BaseDriver.ts
src/driver/Driver.ts
src/driver/ExpressDriver.ts
src/driver/KoaDriver.ts
src/index.ts

Added option to "mount" controllers from a directory under a specific path

"Mount" a directory under a specific path

---

src/RoutingControllerExecutor.ts
src/util/PromiseUtils.ts

Closes #27.
P.S. also some trailing whitespaces removed.

Test action return for a promise using `IsPromiseLike` utility.

---

src/error/BodyRequiredError.ts
src/error/ParameterParseJsonError.ts
src/error/ParameterRequiredError.ts

Use template string

---

src/error/http/MethodNotAllowedError.ts

Refer to [status codes](http://www.restapitutorial.com/httpstatuscodes.html), Method Not Allowed is 405

MethodNotAllowed is 405

---

README.md

Added link to "auto validating action params" description.

Updated Readme's ToC

---

src/error/BadHttpActionError.ts
src/error/BodyRequiredError.ts
src/error/ParameterParseJsonError.ts
src/error/ParameterRequiredError.ts
src/error/http/BadRequestError.ts
src/error/http/ForbiddenError.ts
src/error/http/HttpError.ts
src/error/http/InternalServerError.ts
src/error/http/MethodNotAllowedError.ts
src/error/http/NotAcceptableError.ts
src/error/http/NotFoundError.ts
src/error/http/UnauthorizedError.ts
test/functional/error-subclasses.spec.ts

Updated error subclasses prototype chain

---

src/RoutingControllersOptions.ts
src/decorator/options/ParamOptions.ts
src/driver/BaseDriver.ts
src/driver/Driver.ts
src/index.ts
src/metadata/ParamMetadata.ts
src/metadata/args/ParamMetadataArgs.ts
test/functional/class-validator-options.spec.ts

Fix not working validationOptions and it's type

---

README.md
src/decorator/Session.ts
test/functional/action-params.spec.ts

Fix Session param decorator missing options

---

gulpfile.ts
src/driver/express/ExpressDriver.ts
src/driver/koa/KoaDriver.ts
test/functional/express-middlewares.spec.ts
test/functional/koa-middlewares.spec.ts

This PR fixes an issue with Unhandled promise rejection in non-global middlewares.

fix(Middlewares): catch errors in non-global middlewares

---

.gitignore
README.md
package.json
src/driver/express/ExpressDriver.ts
src/driver/koa/KoaDriver.ts
test/functional/redirect-decorator.spec.ts
tslint.json

1. empty result behave like old one
2. string result override the default in @Redirect
3. object result using template-url to generate url
https://github.com/pleerock/routing-controllers/issues/159

dynamic redirect

---

src/ActionParameterHandler.ts
test/functional/action-params.spec.ts

First of all: thank you for the awesome library.
I recently started to use it and see that there is no solution (or I simple didn't find it) for receive Date type in a query param so I made a little modification to make that possible.

feat(Controller): add date type handling to action parameters

---

src/index.ts

export Driver related types to allow user defined custom drivers

---

src/util/importClassesFromDirectories.ts

fix logic for loading classes from modules

---

src/metadata/ParamMetadata.ts

Fix error on getting type from metadata when no type provided

---

src/driver/express/ExpressDriver.ts
test/functional/render-decorator.spec.ts
test/resources/render-test-locals-spec.html

Re-implement #225 and add test for it.

fix(ExpressDriver): use response.render to render templates

---

src/metadata/ActionMetadata.ts
test/functional/controller-methods.spec.ts

Handle different content-type responses in JsonController

---

src/error/ParamRequiredError.ts

Added the new case so user seeing required BodyParam when missing from POST

Add missing paramater in @bodyParam error message

---

src/ActionParameterHandler.ts
test/functional/class-validator-options.spec.ts

Parameter name in BadRequestError
closes #330

Param name in BadRequestError

---

README.md

[Closes #349] Updated release notes reference

---

src/driver/express/ExpressDriver.ts

Fixes https://github.com/typestack/routing-controllers/issues/505.
We are now able to see the names of the middlewares in the logs. This is the output for the same application used as an example in the reference issue.
```bash
express:router dispatching GET /v1/users/?page=1&limit=100 +10s
express:router query  : /v1/users/?page=1&limit=100 +1ms
express:router expressInit  : /v1/users/?page=1&limit=100 +2ms
express:router corsMiddleware  : /v1/users/?page=1&limit=100 +0ms
express:router HypermediaMiddleware  : /v1/users/?page=1&limit=100 +1ms
express:router BodyParser  : /v1/users/?page=1&limit=100 +0ms
express:router AuthorizationMiddleware  : /v1/users/?page=1&limit=100 +12ms
```

Register named functions in express

---

CHANGELOG.md
package.json

release: 0.9.0

---

README.md

docs: fix code example in README

---

src/metadata-builder/MetadataBuilder.ts
test/unit/controller-inheritance.spec.ts

see https://github.com/typestack/routing-controllers/issues/736
fixes https://github.com/typestack/routing-controllers/issues/736

fix: Controller inheritance Bugfix #736

---

README.md

docs: format README with prettier

---

src/metadata-builder/MetadataBuilder.ts

Update MetadataBuilder.ts - Removed unnecessary assignment of the 'option' parameter

---

package-lock.json
package.json
src/ActionParameterHandler.ts
src/driver/BaseDriver.ts
test/functional/action-options.spec.ts
test/functional/action-params.spec.ts
test/functional/class-transformer-options.spec.ts
test/functional/class-validator-options.spec.ts
test/functional/controller-options.spec.ts

update class-validator and class-transformer peer dependencies 
fixes #783

chore: update class-validator and class-transformer

---

package-lock.json
package.json

Update optional dependencies to latest
Move express and express-session to optiona since they are not required for koa workflow.
fixes #945

chore: update optional dependencies

---

.github/workflows/continuous-deployment-workflow.yml
.github/workflows/continuous-integration-workflow.yml

This PR updates the workflow files to use the LTS and the latest Node versions.
none

build: update workflow files to use lts version

---

src/RoutingControllers.ts
src/driver/BaseDriver.ts
src/driver/express/ExpressDriver.ts

Use route prefix option when registering middlewares
fixes #927

fix: use route prefix when registering middlewares

---

package-lock.json
package.json

update koa dependencies
- koa-multer -> @koa/multer
- koa-router -> @koa/router
- kcors -> @koa/cors
fixes #692

update koa dependencies

---

.github/workflows/auto-approve-dependabot-workflow.yml

add dependabot auto approve workflow

build: add dependabot auto approve workflow

---

package-lock.json
package.json
test/functional/action-params.spec.ts

Update multer to resolve vulnerability CVE-2022-24434
fixes #1031, #1011

chore: update multer

---

CHANGELOG.md
package-lock.json
package.json
src/driver/koa/KoaDriver.ts

This PR creates release v0.10.3

feat: release v0.10.3

---

package-lock.json
package.json

Updated several dependencies and ran `npm audit fix`.

Dependencies updated

---

CHANGELOG.md
package-lock.json
package.json
src/CurrentUserChecker.ts

This PR creates release v0.11.2

feat: release v0.11.2
